-- CreateTable
CREATE TABLE `Marks` (
    `COLOR_CODE` VARCHAR(6) NOT NULL,
    `MARK` VARCHAR(30) NOT NULL,
    `PIN` VARCHAR(30) NOT NULL,

    PRIMARY KEY (`COLOR_CODE`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
