-- CreateTable
CREATE TABLE `Location` (
    `LOCATION_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `LATITUDE` DECIMAL(8, 6) NOT NULL,
    `LONGITUDE` DECIMAL(9, 6) NOT NULL,
    `PLACE_ID` INTEGER NOT NULL,

    UNIQUE INDEX `Location_LATITUDE_LONGITUDE_key`(`LATITUDE`, `LONGITUDE`),
    PRIMARY KEY (`LOCATION_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `SoilType` (
    `LOCATION_ID` INTEGER NOT NULL,
    `DEPTH` SMALLINT NOT NULL,
    `TYPE` TINYINT NOT NULL,

    UNIQUE INDEX `SoilType_LOCATION_ID_DEPTH_TYPE_key`(`LOCATION_ID`, `DEPTH`, `TYPE`),
    PRIMARY KEY (`LOCATION_ID`, `DEPTH`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Place` (
    `PLACE_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `PLACE_NAME` VARCHAR(100) NOT NULL,

    PRIMARY KEY (`PLACE_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `Location` ADD CONSTRAINT `Location_PLACE_ID_fkey` FOREIGN KEY (`PLACE_ID`) REFERENCES `Place`(`PLACE_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `SoilType` ADD CONSTRAINT `SoilType_LOCATION_ID_fkey` FOREIGN KEY (`LOCATION_ID`) REFERENCES `Location`(`LOCATION_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;
